[data]
dir = "/asb-data/"

[network]
listen = ["/ip4/0.0.0.0/tcp/9939"]
external_addresses = []
rendezvous_point = ["/dns4/discover.unstoppableswap.net/tcp/8888/p2p/12D3KooWA6cnqJpVnreBVnoro8midDL9Lpzmg8oJPoAGi7YYaamE", "/dns4/eratosthen.es/tcp/7798/p2p/12D3KooWAh7EXXa2ZyegzLGdjvj1W4G3EXrTGrf6trraoT1MEobs"]

[bitcoin]
electrum_rpc_url = "tcp://mainnet_electrs:50001"
target_block = 1
network = "Mainnet"

[monero]
wallet_rpc_url = "http://mainnet_monero-wallet-rpc:18083/json_rpc"
network = "Mainnet"

[tor]
register_hidden_service = true
hidden_service_num_intro_points = 10

[maker]
min_buy_btc = 0.0004
max_buy_btc = 0.15
ask_spread = 0.00
price_ticker_ws_url = "wss://ws.kraken.com/"
