version: '3'
services:
  stagenet_monerod:
    image: rinocommunity/monero:v0.18.1.2
    restart: unless-stopped
    container_name: stagenet_monerod
    volumes:
      - 'stagenet_monerod-data:/monerod-data/'
    expose:
      - ${MONEROD_PORT:?}
    entrypoint: ''
    command:
      - monerod
      - '--rpc-bind-ip=0.0.0.0'
      - '--rpc-bind-port=${MONEROD_PORT:?}'
      - '--confirm-external-bind'
      - '--restricted-rpc'
      - '--non-interactive'
      - '--enable-dns-blocklist'
      - '--data-dir=/monerod-data/stagenet'
      - '--stagenet'  # Added for stagenet
  stagenet_monero-wallet-rpc:
    container_name: stagenet_monero-wallet-rpc
    image: rinocommunity/monero:v0.18.1.2
    restart: unless-stopped
    depends_on:
      - stagenet_monerod
    volumes:
      - 'stagenet_monero-wallet-rpc-data:/monero-wallet-rpc-data/'
    expose:
      - ${MONERO_WALLET_RPC_PORT:?}
    entrypoint: ''
    command:
      - monero-wallet-rpc
      - '--rpc-bind-ip=0.0.0.0'
      - '--rpc-bind-port=${MONERO_WALLET_RPC_PORT:?}'
      - '--confirm-external-bind'
      - '--daemon-address=stagenet_monerod:${MONEROD_PORT:?}'
      - '--wallet-dir=/monero-wallet-rpc-data/'
      - '--disable-rpc-login'
      - '--trusted-daemon'
      - '--stagenet'  # Added for stagenet
  testnet_bitcoind:
    container_name: testnet_bitcoind
    image: ruimarinho/bitcoin-core:latest
    restart: unless-stopped
    volumes:
      - 'testnet_bitcoind-data:/bitcoind-data/'
    expose:
      - ${BITCOIND_RPC_PORT:?}
      - ${BITCOIND_P2P_PORT:?}
    user: root
    entrypoint: ''
    command:
      - 'bitcoind'
      - '-chain=test'  # Changed to testnet
      - '-server=1'
      - '-prune=0'
      - '-rpcallowip=0.0.0.0/0'
      - '-rpcbind=0.0.0.0:${BITCOIND_RPC_PORT:?}'
      - '-bind=0.0.0.0:${BITCOIND_P2P_PORT:?}'
      - '-datadir=/bitcoind-data/'
      - '-dbcache=16384'
  testnet_electrs:
    container_name: testnet_electrs
    image: getumbrel/electrs:v0.9.9
    restart: unless-stopped
    user: root
    depends_on:
      - testnet_bitcoind
    volumes:
      - 'testnet_bitcoind-data:/bitcoind-data'
      - 'testnet_electrs-data:/electrs-data'
    expose:
      - ${ELECTRS_PORT:?}
    entrypoint: ''
    command:
      - electrs
      - '--network=testnet'  # Changed to testnet
      - '--daemon-dir=/bitcoind-data/'
      - '--daemon-rpc-addr=testnet_bitcoind:${BITCOIND_RPC_PORT:?}'
      - '--daemon-p2p-addr=testnet_bitcoind:${BITCOIND_P2P_PORT:?}'
      - '--db-dir=/electrs-data/db'
      - '--electrum-rpc-addr=0.0.0.0:${ELECTRS_PORT:?}'
      - '--log-filters=INFO'
  stagenet_testnet_asb:
    image: unstoppableswap/asb:latest
    restart: unless-stopped
    container_name: stagenet_testnet_asb
    depends_on:
      - stagenet_monero-wallet-rpc
      - testnet_electrs
    volumes:
      - './config_stagenet_testnet.toml:/asb-data/config_stagenet_testnet.toml'
      - 'stagenet_testnet_asb-data:/asb-data'
    ports:
      - '0.0.0.0:${ASB_PORT:?}:${ASB_PORT:?}'
    entrypoint: ''
    command:
      - 'asb'
      - '--testnet'
      - '--json'
      - '--config=/asb-data/config_stagenet_testnet.toml'
      - 'start'
volumes:
  stagenet_monerod-data:
  stagenet_monero-wallet-rpc-data:
  testnet_bitcoind-data:
  testnet_electrs-data:
  stagenet_testnet_asb-data: