services:
  stagenet_monerod:
    image: ghcr.io/sethforprivacy/simple-monerod:v0.18.4.0
    restart: unless-stopped
    user: root
    container_name: stagenet_monerod
    volumes:
      - 'stagenet_monerod-data:/monerod-data/'
    expose:
      - ${MONEROD_PORT:?}
    entrypoint: ''
    command:
      - monerod
      - '--rpc-bind-ip=0.0.0.0'
      - '--rpc-bind-port=${MONEROD_PORT:?}'
      - '--confirm-external-bind'
      - '--restricted-rpc'
      - '--non-interactive'
      - '--enable-dns-blocklist'
      - '--data-dir=/monerod-data/stagenet'
      - '--stagenet'  # Added for stagenet
  testnet_bitcoind:
    container_name: testnet_bitcoind
    image: getumbrel/bitcoind:v28.0
    restart: unless-stopped
    volumes:
      - 'testnet_bitcoind-data:/bitcoind-data/'
    expose:
      - ${BITCOIND_RPC_PORT:?}
      - ${BITCOIND_P2P_PORT:?}
    user: root
    entrypoint: ''
    command:
      - 'bitcoind'
      - '-chain=test'  # Changed to testnet
      - '-server=1'
      - '-prune=0'
      - '-txindex=1'
      - '-rpcallowip=0.0.0.0/0'
      - '-rpcbind=0.0.0.0:${BITCOIND_RPC_PORT:?}'
      - '-bind=0.0.0.0:${BITCOIND_P2P_PORT:?}'
      - '-datadir=/bitcoind-data/'
      - '-dbcache=16384'
  testnet_electrs:
    container_name: testnet_electrs
    image: getumbrel/electrs:v0.10.6
    restart: unless-stopped
    user: root
    depends_on:
      - testnet_bitcoind
    volumes:
      - 'testnet_bitcoind-data:/bitcoind-data'
      - 'testnet_electrs-data:/electrs-data'
    expose:
      - ${ELECTRS_PORT:?}
    entrypoint: ''
    command:
      - electrs
      - '--network=testnet'  # Changed to testnet
      - '--daemon-dir=/bitcoind-data/'
      - '--daemon-rpc-addr=testnet_bitcoind:${BITCOIND_RPC_PORT:?}'
      - '--daemon-p2p-addr=testnet_bitcoind:${BITCOIND_P2P_PORT:?}'
      - '--db-dir=/electrs-data/db'
      - '--electrum-rpc-addr=0.0.0.0:${ELECTRS_PORT:?}'
      - '--log-filters=INFO'
  testnet_asb:
    image: ghcr.io/unstoppableswap/asb:monero-sys-preview
    restart: unless-stopped
    container_name: testnet_asb
    depends_on:
      - testnet_electrs
    volumes:
      - './config_testnet.toml:/asb-data/config_testnet.toml'
      - 'testnet_asb-data:/asb-data'
    ports:
      - '0.0.0.0:${ASB_PORT:?}:${ASB_PORT:?}'
    entrypoint: ''
    command:
      - 'asb'
      - '--testnet'
      - '--json'
      - '--config=/asb-data/config_testnet.toml'
      - 'start'
volumes:
  stagenet_monerod-data:
  stagenet_monero-wallet-rpc-data: # Keeping this here for now to avoid the volume being pruned by docker
  testnet_bitcoind-data:
  testnet_electrs-data:
  testnet_asb-data:
